### PR TITLE
Added full backend boilerpate with Docker

### PR DESCRIPTION
**Pull request by EduRibeiro00**
Added full backend boilerplate, with Docker support.
This PR includes the setup of two environments, `dev` (for development of the application) and `prod` (for production), each with their respective Dockerfiles and docker-compose files.

Dev environment uses the following containers: `Django`, `PostgreSQL`, `pgAdmin`.
Prod environment uses the following containers: `Django`, `PostgreSQL`, `pgAdmin`, `nginx`.

Please test if the code is working properly both in the development environment `docker-compose up --build`and in the production environment `docker-compose -f docker-compose.prod.yml up --build`.

Closes issues #1, #2.

### CODE REVIEW

**Review by kiko-g — DISMISSED** [review]
Tested locally and it worked 🤩

**Comment by FilipePintoReis** [comment]
The server doesn't seem to be working, but maybe I'm doing something wrong?

> feupexchange_django | standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by FilipePintoReis** [comment]
I will accept this PR on the condition that before it is sent to production we make the .env.prod invisible.

**Comment by EduRibeiro00** [comment]
With the recent changes to the Django Dockerfiles, the server should be working properly. The `.env.prod` file should serve as a template to insert the actual environment variables that are used in the project; those should not be pushed to the remote repository.

@NIAEFEUP/feup-exchange please review the PR again and make sure you can start the backend services with no problems.

**Review by kiko-g — DISMISSED** [review]
Worked on my machine but on windows you might have issues with carriage return (CRLF)

**Review by FilipePintoReis — APPROVED** [review]

**Review by kiko-g — APPROVED** [review]
Worked on my machine 😀 

PS: Be careful with end of line on `entrypoint.sh` and `entrypoint.prod.sh`

**Review by Jumaruba — APPROVED** [review]

**Pull request merged**
